apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentinel-ingress
  namespace: lms-sentinel
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: sentinel.consumeraffairs.gov.in
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: core-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-dashboard
                port:
                  number: 80
